// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vishipel.Infrastructure.Data;

#nullable disable

namespace Vishipel.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516142005_AddLogisticsAndFinancialFields")]
    partial class AddLogisticsAndFinancialFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vishipel.Core.Models.CauHinhHeThong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BanQuyen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EmailLienHe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Hotline")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slogan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SmtpPass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<string>("SmtpServer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenWebsite")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("CauHinhHeThong", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.ChiNhanh", b =>
                {
                    b.Property<byte>("MaChiNhanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("MaChiNhanh"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChiNhanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChiNhanh");

                    b.ToTable("ChiNhanh", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaThietBi")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("InstallLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumbersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDonHang", "MaThietBi");

                    b.HasIndex("MaThietBi");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.ChiTietNhapKho", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .HasColumnType("int");

                    b.Property<int>("MaThietBi")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGiaNhap")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuNhap", "MaThietBi");

                    b.HasIndex("MaThietBi");

                    b.ToTable("ChiTietNhapKho", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.ChiTietXuatKho", b =>
                {
                    b.Property<int>("MaPhieuXuat")
                        .HasColumnType("int");

                    b.Property<int>("MaThietBi")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGiaBan")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuXuat", "MaThietBi");

                    b.HasIndex("MaThietBi");

                    b.ToTable("ChiTietXuatKho", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.DanhMucSeri", b =>
                {
                    b.Property<string>("MaSeri")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaHopDong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("MaKho")
                        .HasColumnType("tinyint");

                    b.Property<int?>("MaThietBi")
                        .HasColumnType("int");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaSeri");

                    b.HasIndex("MaHopDong");

                    b.HasIndex("MaKho");

                    b.HasIndex("MaThietBi");

                    b.ToTable("DanhMucSeri", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.DonDatHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<string>("BillingInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDepositPaid")
                        .HasColumnType("bit");

                    b.Property<int?>("MaKH")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuoteRequestId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ShippingCost")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("ShippingMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongGiaTri")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<byte?>("WarehouseId")
                        .HasColumnType("tinyint");

                    b.Property<string>("WarrantyTerms")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDonHang");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaTaiKhoan");

                    b.HasIndex("QuoteRequestId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("DonDatHang", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.DonViTinh", b =>
                {
                    b.Property<byte>("MaDVT")
                        .HasColumnType("tinyint");

                    b.Property<string>("TenDVT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDVT");

                    b.ToTable("DonViTinh", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BuyerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<string>("MaHopDong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ThueSuat")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaDonHang")
                        .IsUnique()
                        .HasFilter("[MaDonHang] IS NOT NULL");

                    b.HasIndex("MaHopDong");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.HopDong", b =>
                {
                    b.Property<string>("MaHopDong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("GiaTriHopDong")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungTomTat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartyAName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("MaHopDong");

                    b.HasIndex("MaDonHang")
                        .IsUnique()
                        .HasFilter("[MaDonHang] IS NOT NULL");

                    b.ToTable("HopDong", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.KeHoachCongNo", b =>
                {
                    b.Property<int>("MaKeHoach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKeHoach"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("HanThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<string>("MaHopDong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Percentage")
                        .HasColumnType("int");

                    b.Property<string>("PhaseName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PhaseOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienDuKien")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKeHoach");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaHopDong");

                    b.ToTable("KeHoachCongNo", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LoaiKhachHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MST")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.Kho", b =>
                {
                    b.Property<byte>("MaKho")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("MaChiNhanh")
                        .HasColumnType("tinyint");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKho");

                    b.HasIndex("MaChiNhanh");

                    b.ToTable("Kho", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.LoaiThietBi", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiThietBi", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNCC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNCC"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MST")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NguoiLienHe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaNCC");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.NhatKyHeThong", b =>
                {
                    b.Property<int>("MaLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLog"));

                    b.Property<string>("DiaChiIP")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("HanhDong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLog");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("NhatKyHeThong", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.PhieuChi", b =>
                {
                    b.Property<int>("MaPhieuChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuChi"));

                    b.Property<int?>("MaNCC")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhieuNhap")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayChi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoPhieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("MaPhieuChi");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaPhieuNhap");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("PhieuChi", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.PhieuNhapKho", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuNhap"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte?>("MaKho")
                        .HasColumnType("tinyint");

                    b.Property<int?>("MaNCC")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("MaKho");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("PhieuNhapKho", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.PhieuThu", b =>
                {
                    b.Property<int>("MaPhieuThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuThu"));

                    b.Property<string>("HinhThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaHopDong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaKH")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThu")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoPhieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("MaPhieuThu");

                    b.HasIndex("MaHopDong");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("PhieuThu", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.PhieuXuatKho", b =>
                {
                    b.Property<int>("MaPhieuXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuXuat"));

                    b.Property<string>("LyDoXuat")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaHopDong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("MaKho")
                        .HasColumnType("tinyint");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhieuXuat");

                    b.HasIndex("MaHopDong");

                    b.HasIndex("MaKho");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("PhieuXuatKho", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.QuoteRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminReply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalQuotedPrice")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("QuoteRequests", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.QuoteRequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("QuoteRequestId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ReferencePrice")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteRequestId");

                    b.ToTable("QuoteRequestItems", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte?>("MaVaiTro")
                        .HasColumnType("tinyint");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.ThanhLyHangHoa", b =>
                {
                    b.Property<int>("MaThanhLy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhLy"));

                    b.Property<string>("LyDo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte?>("MaKho")
                        .HasColumnType("tinyint");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<int?>("MaThietBi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayThanhLy")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaThanhLy");

                    b.HasIndex("MaKho");

                    b.HasIndex("MaTaiKhoan");

                    b.HasIndex("MaThietBi");

                    b.ToTable("ThanhLyHangHoa", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.ThietBi", b =>
                {
                    b.Property<int>("MaThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThietBi"));

                    b.Property<byte>("BaoHanhThang")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("DiemDanhGia")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("GiaBan")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("HangSanXuat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HinhAnhJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int");

                    b.Property<byte?>("MaDVT")
                        .HasColumnType("tinyint");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("MoTaChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaNgan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ThongSoKyThuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.Property<string>("XuatXu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaThietBi");

                    b.HasIndex("MaDVT");

                    b.HasIndex("MaLoai");

                    b.ToTable("ThietBi", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.TonKhoChiTiet", b =>
                {
                    b.Property<byte>("MaKho")
                        .HasColumnType("tinyint");

                    b.Property<int>("MaThietBi")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("MaKho", "MaThietBi");

                    b.HasIndex("MaThietBi");

                    b.ToTable("TonKhoChiTiet", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.VaiTro", b =>
                {
                    b.Property<byte>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.YeuCauHoTro", b =>
                {
                    b.Property<int>("MaYeuCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaYeuCau"));

                    b.Property<string>("CongTy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LoaiYeuCau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaYeuCau");

                    b.ToTable("YeuCauHoTro", (string)null);
                });

            modelBuilder.Entity("Vishipel.Core.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("Vishipel.Core.Models.DonDatHang", "DonDatHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vishipel.Core.Models.ThietBi", "ThietBi")
                        .WithMany()
                        .HasForeignKey("MaThietBi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonDatHang");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("Vishipel.Core.Models.ChiTietNhapKho", b =>
                {
                    b.HasOne("Vishipel.Core.Models.PhieuNhapKho", "PhieuNhapKho")
                        .WithMany("ChiTietNhapKhos")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vishipel.Core.Models.ThietBi", "ThietBi")
                        .WithMany()
                        .HasForeignKey("MaThietBi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhapKho");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("Vishipel.Core.Models.ChiTietXuatKho", b =>
                {
                    b.HasOne("Vishipel.Core.Models.PhieuXuatKho", "PhieuXuatKho")
                        .WithMany("ChiTietXuatKhos")
                        .HasForeignKey("MaPhieuXuat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vishipel.Core.Models.ThietBi", "ThietBi")
                        .WithMany()
                        .HasForeignKey("MaThietBi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuXuatKho");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("Vishipel.Core.Models.DanhMucSeri", b =>
                {
                    b.HasOne("Vishipel.Core.Models.HopDong", "HopDong")
                        .WithMany()
                        .HasForeignKey("MaHopDong");

                    b.HasOne("Vishipel.Core.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("MaKho");

                    b.HasOne("Vishipel.Core.Models.ThietBi", "ThietBi")
                        .WithMany()
                        .HasForeignKey("MaThietBi");

                    b.Navigation("HopDong");

                    b.Navigation("Kho");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("Vishipel.Core.Models.DonDatHang", b =>
                {
                    b.HasOne("Vishipel.Core.Models.TaiKhoan", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId");

                    b.HasOne("Vishipel.Core.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH");

                    b.HasOne("Vishipel.Core.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan");

                    b.HasOne("Vishipel.Core.Models.QuoteRequest", "QuoteRequest")
                        .WithMany()
                        .HasForeignKey("QuoteRequestId");

                    b.HasOne("Vishipel.Core.Models.Kho", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId");

                    b.Navigation("Assignee");

                    b.Navigation("KhachHang");

                    b.Navigation("QuoteRequest");

                    b.Navigation("TaiKhoan");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Vishipel.Core.Models.HoaDon", b =>
                {
                    b.HasOne("Vishipel.Core.Models.DonDatHang", "DonDatHang")
                        .WithOne("Invoice")
                        .HasForeignKey("Vishipel.Core.Models.HoaDon", "MaDonHang");

                    b.HasOne("Vishipel.Core.Models.HopDong", "HopDong")
                        .WithMany()
                        .HasForeignKey("MaHopDong");

                    b.Navigation("DonDatHang");

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("Vishipel.Core.Models.HopDong", b =>
                {
                    b.HasOne("Vishipel.Core.Models.DonDatHang", "DonDatHang")
                        .WithOne("Contract")
                        .HasForeignKey("Vishipel.Core.Models.HopDong", "MaDonHang");

                    b.Navigation("DonDatHang");
                });

            modelBuilder.Entity("Vishipel.Core.Models.KeHoachCongNo", b =>
                {
                    b.HasOne("Vishipel.Core.Models.DonDatHang", "DonDatHang")
                        .WithMany("PaymentSchedules")
                        .HasForeignKey("MaDonHang");

                    b.HasOne("Vishipel.Core.Models.HopDong", "HopDong")
                        .WithMany()
                        .HasForeignKey("MaHopDong");

                    b.Navigation("DonDatHang");

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("Vishipel.Core.Models.Kho", b =>
                {
                    b.HasOne("Vishipel.Core.Models.ChiNhanh", "ChiNhanh")
                        .WithMany()
                        .HasForeignKey("MaChiNhanh");

                    b.Navigation("ChiNhanh");
                });

            modelBuilder.Entity("Vishipel.Core.Models.NhatKyHeThong", b =>
                {
                    b.HasOne("Vishipel.Core.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Vishipel.Core.Models.PhieuChi", b =>
                {
                    b.HasOne("Vishipel.Core.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("MaNCC");

                    b.HasOne("Vishipel.Core.Models.PhieuNhapKho", "PhieuNhapKho")
                        .WithMany()
                        .HasForeignKey("MaPhieuNhap");

                    b.HasOne("Vishipel.Core.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan");

                    b.Navigation("NhaCungCap");

                    b.Navigation("PhieuNhapKho");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Vishipel.Core.Models.PhieuNhapKho", b =>
                {
                    b.HasOne("Vishipel.Core.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("MaKho");

                    b.HasOne("Vishipel.Core.Models.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("MaNCC");

                    b.HasOne("Vishipel.Core.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan");

                    b.Navigation("Kho");

                    b.Navigation("NhaCungCap");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Vishipel.Core.Models.PhieuThu", b =>
                {
                    b.HasOne("Vishipel.Core.Models.HopDong", "HopDong")
                        .WithMany()
                        .HasForeignKey("MaHopDong");

                    b.HasOne("Vishipel.Core.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH");

                    b.HasOne("Vishipel.Core.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan");

                    b.Navigation("HopDong");

                    b.Navigation("KhachHang");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Vishipel.Core.Models.PhieuXuatKho", b =>
                {
                    b.HasOne("Vishipel.Core.Models.HopDong", "HopDong")
                        .WithMany()
                        .HasForeignKey("MaHopDong");

                    b.HasOne("Vishipel.Core.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("MaKho");

                    b.HasOne("Vishipel.Core.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan");

                    b.Navigation("HopDong");

                    b.Navigation("Kho");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Vishipel.Core.Models.QuoteRequest", b =>
                {
                    b.HasOne("Vishipel.Core.Models.TaiKhoan", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vishipel.Core.Models.QuoteRequestItem", b =>
                {
                    b.HasOne("Vishipel.Core.Models.QuoteRequest", "QuoteRequest")
                        .WithMany("Items")
                        .HasForeignKey("QuoteRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteRequest");
                });

            modelBuilder.Entity("Vishipel.Core.Models.TaiKhoan", b =>
                {
                    b.HasOne("Vishipel.Core.Models.VaiTro", "VaiTro")
                        .WithMany()
                        .HasForeignKey("MaVaiTro");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("Vishipel.Core.Models.ThanhLyHangHoa", b =>
                {
                    b.HasOne("Vishipel.Core.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("MaKho");

                    b.HasOne("Vishipel.Core.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan");

                    b.HasOne("Vishipel.Core.Models.ThietBi", "ThietBi")
                        .WithMany()
                        .HasForeignKey("MaThietBi");

                    b.Navigation("Kho");

                    b.Navigation("TaiKhoan");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("Vishipel.Core.Models.ThietBi", b =>
                {
                    b.HasOne("Vishipel.Core.Models.DonViTinh", "DonViTinh")
                        .WithMany()
                        .HasForeignKey("MaDVT");

                    b.HasOne("Vishipel.Core.Models.LoaiThietBi", "LoaiThietBi")
                        .WithMany("ThietBis")
                        .HasForeignKey("MaLoai");

                    b.Navigation("DonViTinh");

                    b.Navigation("LoaiThietBi");
                });

            modelBuilder.Entity("Vishipel.Core.Models.TonKhoChiTiet", b =>
                {
                    b.HasOne("Vishipel.Core.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("MaKho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vishipel.Core.Models.ThietBi", "ThietBi")
                        .WithMany()
                        .HasForeignKey("MaThietBi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kho");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("Vishipel.Core.Models.DonDatHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("Contract");

                    b.Navigation("Invoice");

                    b.Navigation("PaymentSchedules");
                });

            modelBuilder.Entity("Vishipel.Core.Models.LoaiThietBi", b =>
                {
                    b.Navigation("ThietBis");
                });

            modelBuilder.Entity("Vishipel.Core.Models.PhieuNhapKho", b =>
                {
                    b.Navigation("ChiTietNhapKhos");
                });

            modelBuilder.Entity("Vishipel.Core.Models.PhieuXuatKho", b =>
                {
                    b.Navigation("ChiTietXuatKhos");
                });

            modelBuilder.Entity("Vishipel.Core.Models.QuoteRequest", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
